version: '3.8'

services:
  mongo:
    build:
      context: ./mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:${DATA_DIR}/mongo/data
      # Bind-mount init.js and :ro makes it read-only
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    restart: unless-stopped

  postgres:
    build:
      context: ./postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:${DATA_DIR}/postgres/data

  redis:
    build:
      context: ./redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:${DATA_DIR}/redis/data

volumes:
  mongo-data:
  postgres-data:
  redis-data: